// @ts-check
import { defineConfig } from 'astro/config'
import starlight from '@astrojs/starlight'

/**
 * just-a-bot's documentation site.
 *
 * **Two rendered source trees, and that is the whole design of this one.** The
 * repo already had 21 hand-written pages under `docs/` (the user-facing manual:
 * what each command does) alongside 9 corpus wiki pages (the maintainer's
 * synthesis: why it is shaped that way). Neither restates the other, so both are
 * rendered, into separate sections, by scripts/sync-corpus.mjs.
 *
 * The site itself lives in `docs-site/` rather than `docs/` precisely because
 * `docs/` was already taken by real content. The deployed URL is unaffected —
 * that comes from the estate's DocsSite construct, not from this directory name.
 *
 *   • Manual   → docs/**\/*.md            → /manual/...
 *   • Wiki     → corpus/wiki/*.md, log.md → /wiki/...
 *   • Reference→ TypeDoc over @bots/shared
 *   • Diagrams → archify, from diagrams/
 *
 * Deployed at https://gandolh.ro/just-a-bot/docs/.
 */
// The deployed base path, baked in rather than injected at deploy time.
//
// vps-deploy ships what this repo already built and VERIFIES this base — it does
// not set it. That is the estate's rule for the case that matters most (Ward's
// UI does the same, see vps-deploy/stacks/ward.ts): a variable the deploy passes
// that changes nothing is a variable that can silently disagree, whereas a value
// baked here and checked there cannot. Build with `npm run docs`; a wrong base
// fails the deploy by name instead of shipping a page whose every asset 404s.
//
// DOCS_BASE still overrides it, for building a copy to serve from somewhere else.
const base = process.env.DOCS_BASE ?? '/just-a-bot/docs/'

export default defineConfig({
  base,
  site: 'https://gandolh.ro',
  integrations: [
    starlight({
      title: 'just-a-bot',
      description:
        'A personal Discord bot — games, gambling, AI chat, image generation, reminders and an RPG world.',
      tagline: 'One repo, one bot, a lot of commands.',
      customCss: ['./src/styles/theme.css'],
      social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/gandolh/just-a-bot' }],
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'What just-a-bot is', link: '/' },
            { label: 'Overview', link: '/wiki/overview/' },
            { label: 'Architecture', link: '/wiki/architecture/' },
            { label: 'Setup', link: '/manual/discord/setup/' },
          ],
        },
        // Autogenerated from the rendered manual tree. Starlight ≥0.39 requires
        // the autogenerate config to sit inside `items` rather than beside a
        // `label`, so the group is written out longhand.
        {
          label: 'Manual — the commands',
          items: [{ autogenerate: { directory: 'manual/discord' } }],
        },
        {
          label: 'Manual — common',
          items: [{ autogenerate: { directory: 'manual/common' } }],
        },
        {
          label: 'Maintainer — from the corpus',
          items: [
            { label: 'Decisions', link: '/wiki/decisions/' },
            { label: 'Glossary', link: '/wiki/glossary/' },
            { label: 'The code graph', link: '/wiki/code-graph/' },
            { label: 'Open questions', link: '/wiki/open-questions/' },
          ],
        },
        {
          label: 'Reference and state',
          items: [
            { label: '@bots/shared (TypeDoc) ↗', link: '/reference/', attrs: { target: '_blank' } },
            { label: 'Status', link: '/wiki/status/' },
            { label: 'Change log', link: '/wiki/log/' },
          ],
        },
      ],
    }),
  ],
})
