export interface FallbackQuestion {
  question: string;
  correct: string;
  incorrect: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const fallbackQuestions: FallbackQuestion[] = [
  // Science
  {
    question: 'What is the chemical symbol for gold?',
    correct: 'Au',
    incorrect: ['Ag', 'Fe', 'Cu'],
    category: 'Science',
    difficulty: 'easy',
  },
  {
    question: 'How many bones are in the adult human body?',
    correct: '206',
    incorrect: ['196', '216', '226'],
    category: 'Science',
    difficulty: 'easy',
  },
  {
    question: 'What is the speed of light in a vacuum (approximately)?',
    correct: '299,792 km/s',
    incorrect: ['199,792 km/s', '399,792 km/s', '499,792 km/s'],
    category: 'Science',
    difficulty: 'medium',
  },
  {
    question: 'What planet is known as the Red Planet?',
    correct: 'Mars',
    incorrect: ['Venus', 'Jupiter', 'Saturn'],
    category: 'Science',
    difficulty: 'easy',
  },
  {
    question: 'What is the atomic number of carbon?',
    correct: '6',
    incorrect: ['4', '8', '12'],
    category: 'Science',
    difficulty: 'easy',
  },
  {
    question: 'Which gas makes up about 78% of Earth\'s atmosphere?',
    correct: 'Nitrogen',
    incorrect: ['Oxygen', 'Carbon dioxide', 'Argon'],
    category: 'Science',
    difficulty: 'easy',
  },
  {
    question: 'What is the powerhouse of the cell?',
    correct: 'Mitochondria',
    incorrect: ['Nucleus', 'Ribosome', 'Golgi apparatus'],
    category: 'Science',
    difficulty: 'easy',
  },
  {
    question: 'What phenomenon explains why the sky is blue?',
    correct: 'Rayleigh scattering',
    incorrect: ['Mie scattering', 'Diffraction', 'Refraction'],
    category: 'Science',
    difficulty: 'hard',
  },
  {
    question: 'What is the half-life of Carbon-14?',
    correct: '5,730 years',
    incorrect: ['1,000 years', '10,000 years', '50,000 years'],
    category: 'Science',
    difficulty: 'hard',
  },
  {
    question: 'What is the most abundant element in the universe?',
    correct: 'Hydrogen',
    incorrect: ['Helium', 'Carbon', 'Oxygen'],
    category: 'Science',
    difficulty: 'easy',
  },
  // History
  {
    question: 'In what year did World War II end?',
    correct: '1945',
    incorrect: ['1943', '1944', '1946'],
    category: 'History',
    difficulty: 'easy',
  },
  {
    question: 'Who was the first President of the United States?',
    correct: 'George Washington',
    incorrect: ['Thomas Jefferson', 'John Adams', 'Benjamin Franklin'],
    category: 'History',
    difficulty: 'easy',
  },
  {
    question: 'Which empire was ruled by Genghis Khan?',
    correct: 'Mongol Empire',
    incorrect: ['Ottoman Empire', 'Roman Empire', 'Han Dynasty'],
    category: 'History',
    difficulty: 'easy',
  },
  {
    question: 'In what year did the French Revolution begin?',
    correct: '1789',
    incorrect: ['1776', '1799', '1804'],
    category: 'History',
    difficulty: 'medium',
  },
  {
    question: 'What ancient wonder was located in Alexandria?',
    correct: 'The Lighthouse',
    incorrect: ['The Colossus', 'The Hanging Gardens', 'The Great Pyramid'],
    category: 'History',
    difficulty: 'medium',
  },
  {
    question: 'Who wrote the Declaration of Independence?',
    correct: 'Thomas Jefferson',
    incorrect: ['Benjamin Franklin', 'John Adams', 'George Washington'],
    category: 'History',
    difficulty: 'easy',
  },
  {
    question: 'The Berlin Wall fell in what year?',
    correct: '1989',
    incorrect: ['1987', '1991', '1985'],
    category: 'History',
    difficulty: 'easy',
  },
  {
    question: 'Who was known as the Sun King of France?',
    correct: 'Louis XIV',
    incorrect: ['Louis XVI', 'Napoleon Bonaparte', 'Francis I'],
    category: 'History',
    difficulty: 'medium',
  },
  // Geography
  {
    question: 'What is the capital of Australia?',
    correct: 'Canberra',
    incorrect: ['Sydney', 'Melbourne', 'Brisbane'],
    category: 'Geography',
    difficulty: 'medium',
  },
  {
    question: 'What is the longest river in the world?',
    correct: 'Nile',
    incorrect: ['Amazon', 'Yangtze', 'Mississippi'],
    category: 'Geography',
    difficulty: 'easy',
  },
  {
    question: 'Which country has the most natural lakes?',
    correct: 'Canada',
    incorrect: ['Russia', 'United States', 'Finland'],
    category: 'Geography',
    difficulty: 'medium',
  },
  {
    question: 'What is the smallest country in the world?',
    correct: 'Vatican City',
    incorrect: ['Monaco', 'San Marino', 'Liechtenstein'],
    category: 'Geography',
    difficulty: 'easy',
  },
  {
    question: 'On which continent is the Sahara Desert located?',
    correct: 'Africa',
    incorrect: ['Asia', 'South America', 'Australia'],
    category: 'Geography',
    difficulty: 'easy',
  },
  {
    question: 'What is the tallest mountain in the world?',
    correct: 'Mount Everest',
    incorrect: ['K2', 'Kangchenjunga', 'Lhotse'],
    category: 'Geography',
    difficulty: 'easy',
  },
  // Entertainment
  {
    question: 'In the Harry Potter series, what house is Harry sorted into?',
    correct: 'Gryffindor',
    incorrect: ['Slytherin', 'Ravenclaw', 'Hufflepuff'],
    category: 'Entertainment',
    difficulty: 'easy',
  },
  {
    question: 'Which movie features the character Jack Sparrow?',
    correct: 'Pirates of the Caribbean',
    incorrect: ['The Mask of Zorro', 'Treasure Planet', 'Hook'],
    category: 'Entertainment',
    difficulty: 'easy',
  },
  {
    question: 'What is the name of the fictional African country in "Black Panther"?',
    correct: 'Wakanda',
    incorrect: ['Zamunda', 'Genosha', 'Latveria'],
    category: 'Entertainment',
    difficulty: 'easy',
  },
  {
    question: 'How many episodes are in the first season of Breaking Bad?',
    correct: '7',
    incorrect: ['10', '13', '5'],
    category: 'Entertainment',
    difficulty: 'hard',
  },
  {
    question: 'Who directed the movie "Inception"?',
    correct: 'Christopher Nolan',
    incorrect: ['Steven Spielberg', 'James Cameron', 'Ridley Scott'],
    category: 'Entertainment',
    difficulty: 'easy',
  },
  // General Knowledge
  {
    question: 'How many sides does a hexagon have?',
    correct: '6',
    incorrect: ['5', '7', '8'],
    category: 'General Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What is the square root of 144?',
    correct: '12',
    incorrect: ['11', '13', '14'],
    category: 'General Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What is the largest ocean on Earth?',
    correct: 'Pacific Ocean',
    incorrect: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'],
    category: 'General Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'In which sport would you perform a "slam dunk"?',
    correct: 'Basketball',
    incorrect: ['Volleyball', 'Tennis', 'Football'],
    category: 'General Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'How many strings does a standard guitar have?',
    correct: '6',
    incorrect: ['4', '5', '8'],
    category: 'General Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What language has the most native speakers in the world?',
    correct: 'Mandarin Chinese',
    incorrect: ['English', 'Spanish', 'Hindi'],
    category: 'General Knowledge',
    difficulty: 'medium',
  },
  {
    question: 'What is the chemical formula for water?',
    correct: 'H2O',
    incorrect: ['H2O2', 'CO2', 'NaCl'],
    category: 'General Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'Who painted the Mona Lisa?',
    correct: 'Leonardo da Vinci',
    incorrect: ['Michelangelo', 'Raphael', 'Rembrandt'],
    category: 'General Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What is the hardest natural substance on Earth?',
    correct: 'Diamond',
    incorrect: ['Quartz', 'Titanium', 'Corundum'],
    category: 'General Knowledge',
    difficulty: 'easy',
  },
  {
    question: 'What year was the World Wide Web invented?',
    correct: '1989',
    incorrect: ['1983', '1995', '1991'],
    category: 'General Knowledge',
    difficulty: 'medium',
  },
  // Sports
  {
    question: 'How many players are on a standard soccer team?',
    correct: '11',
    incorrect: ['9', '12', '10'],
    category: 'Sports',
    difficulty: 'easy',
  },
  {
    question: 'In which city were the first modern Olympic Games held?',
    correct: 'Athens',
    incorrect: ['Paris', 'London', 'Rome'],
    category: 'Sports',
    difficulty: 'medium',
  },
  {
    question: 'What is the maximum score in a single game of bowling?',
    correct: '300',
    incorrect: ['270', '290', '310'],
    category: 'Sports',
    difficulty: 'easy',
  },
  {
    question: 'How many Grand Slam tournaments are there in tennis?',
    correct: '4',
    incorrect: ['3', '5', '6'],
    category: 'Sports',
    difficulty: 'easy',
  },
  {
    question: 'In which sport is the Stanley Cup awarded?',
    correct: 'Ice Hockey',
    incorrect: ['Basketball', 'Baseball', 'Football'],
    category: 'Sports',
    difficulty: 'easy',
  },
  // Food & Drink
  {
    question: 'What is the main ingredient in guacamole?',
    correct: 'Avocado',
    incorrect: ['Tomato', 'Lime', 'Onion'],
    category: 'Food & Drink',
    difficulty: 'easy',
  },
  {
    question: 'Which country is the origin of sushi?',
    correct: 'Japan',
    incorrect: ['China', 'Korea', 'Thailand'],
    category: 'Food & Drink',
    difficulty: 'easy',
  },
  {
    question: 'What type of pasta is shaped like small rice grains?',
    correct: 'Orzo',
    incorrect: ['Penne', 'Farfalle', 'Rotini'],
    category: 'Food & Drink',
    difficulty: 'medium',
  },
  {
    question: 'What is the world\'s most expensive spice by weight?',
    correct: 'Saffron',
    incorrect: ['Vanilla', 'Cardamom', 'Black pepper'],
    category: 'Food & Drink',
    difficulty: 'medium',
  },
  {
    question: 'Brie is a type of cheese from which country?',
    correct: 'France',
    incorrect: ['Italy', 'Switzerland', 'Netherlands'],
    category: 'Food & Drink',
    difficulty: 'easy',
  },
];
