export const WORDS: Record<string, string[]> = {
  animals: [
    'elephant', 'giraffe', 'dolphin', 'penguin', 'cheetah',
    'kangaroo', 'crocodile', 'flamingo', 'gorilla', 'hamster',
    'jaguar', 'leopard', 'mongoose', 'narwhal', 'ostrich',
    'platypus', 'rhinoceros', 'salamander', 'tortoise', 'vulture',
    'wolverine', 'zebra', 'antelope', 'capybara', 'chameleon',
    'cockatoo', 'coyote', 'dingo', 'ferret', 'gazelle',
    'iguana', 'lemur', 'lynx', 'manatee', 'meerkat',
    'ocelot', 'panther', 'porcupine', 'raccoon', 'tapir',
  ],
  food: [
    'pineapple', 'broccoli', 'avocado', 'blueberry', 'cauliflower',
    'cinnamon', 'croissant', 'eggplant', 'guacamole', 'hummus',
    'jalapeño', 'lasagna', 'mozzarella', 'pancake', 'raspberry',
    'risotto', 'sriracha', 'strawberry', 'tiramisu', 'zucchini',
    'artichoke', 'asparagus', 'cabbage', 'cantaloupe', 'cardamom',
    'cashew', 'cilantro', 'clementine', 'courgette', 'cranberry',
    'edamame', 'espresso', 'focaccia', 'gnocchi', 'granola',
    'kiwifruit', 'kumquat', 'macaron', 'nectarine', 'papaya',
  ],
  tech: [
    'typescript', 'kubernetes', 'javascript', 'algorithm', 'bandwidth',
    'blockchain', 'compiler', 'database', 'encryption', 'firmware',
    'framework', 'hypertext', 'interface', 'latency', 'middleware',
    'namespace', 'parameter', 'permalink', 'pipeline', 'protocol',
    'recursion', 'refactor', 'repository', 'runtime', 'sandbox',
    'serverless', 'singleton', 'stylesheet', 'terminal', 'variable',
    'webhook', 'websocket', 'abstraction', 'boolean', 'bytecode',
    'callback', 'container', 'debugger', 'deployment', 'endpoint',
  ],
  countries: [
    'australia', 'brazil', 'canada', 'denmark', 'ethiopia',
    'finland', 'guatemala', 'honduras', 'indonesia', 'jamaica',
    'kazakhstan', 'luxembourg', 'madagascar', 'nicaragua', 'paraguay',
    'philippines', 'portugal', 'singapore', 'slovakia', 'switzerland',
    'tanzania', 'thailand', 'ukraine', 'uruguay', 'venezuela',
    'argentina', 'cambodia', 'colombia', 'ecuador', 'ghana',
    'iceland', 'jordan', 'kenya', 'malaysia', 'morocco',
    'nigeria', 'pakistan', 'romania', 'senegal', 'vietnam',
  ],
  sports: [
    'badminton', 'baseball', 'basketball', 'bobsled', 'cricket',
    'cycling', 'football', 'gymnastics', 'handball', 'hockey',
    'judo', 'kayaking', 'lacrosse', 'marathon', 'pentathlon',
    'rowing', 'skiing', 'snowboard', 'softball', 'surfing',
    'swimming', 'taekwondo', 'triathlon', 'volleyball', 'weightlifting',
    'wrestling', 'archery', 'biathlon', 'canoeing', 'curling',
    'decathlon', 'equestrian', 'fencing', 'hurdles', 'javelin',
    'netball', 'rugby', 'sailing', 'skeleton', 'squash',
  ],
};

export const ALL_CATEGORIES = Object.keys(WORDS);
